### PR TITLE
Output of output_index_errors()

### LINKED ISSUE #2240: BUG: Command Line Undefined Variable Warning Notice Flood
When performing a command line sync in blocks of 350 we get the following notice three times:

`Warning: Request Entity Too Large`

Followed by a warning flood:

`PHP Notice:  Undefined variable: item in elasticpress/includes/classes/Command.php on line 960`

Followed by a further flood:

```
PHP Notice: Undefined index: type in elasticpress/includes/classes/Command.php on line 1021
PHP Notice: Undefined index: reason in elasticpress/includes/classes/Command.php on line 1022
PHP Notice: Undefined index: type in elasticpress/includes/classes/Command.php on line 1027
```

We can see that the _$attempts_ for loop is hitting the **continue** statement on line 941 meaning that we never get to the **if/else** statement on line 944.

This means that when we get to line 959 _$index_objects_ hasn't been reset (line 951) and _$item_ does not exist (line 945) hence the warning flood.

Whilst the **foreach** of line 959 could be guarded with a check to see if $_item_ is set, we're not sure whether this is appropriate as we don't understand enough about the code to know what this **foreach** is doing and why it's using $_item_.

**Steps to Reproduce**
1. Visit top level WP directory.
2. Run the command: 
`wp elasticpress index --setup`

3. Observe the warning flood.

**Expected behavior**
Warning that the Request entity is too large without the flood of "undefined variable" warning messages.

**Environment information**
 - Device: Desktop PC 
 - OS: Debian 10 buster
 - WordPress version: 5.7.2
 - ElasticPress version: 3.5.6
 - Elasticsearch version: 7.13.2
 - Where do you host your Elasticsearch server? localhost

### PR DESCRIPTION
**Pull request by felipeelia**
### Description of the Change

Check if some keys exist in `$error` before using them.

### Applicable Issues

Closes #2240

### Changelog Entry

Fixed output of WP-CLI errors

### CODE REVIEW

File: includes/classes/Command.php [hunk 1]
```diff
@@ -1048,15 +1048,20 @@ private function output_index_errors( $errors, Indexable $indexable, $output = t
...
-				$error['type'],
-				$error['reason'],
+				$error_type,
+				$error_reason,
 			);
 
 			$error_text .= '- ' . $object_id . ' (' . $indexable->labels['singular'] . '): ' . "\r\n";
 
-			$error_text .= '[' . $error['type'] . '] ' . $error['reason'] . "\r\n";
+			if ( ! empty( $error_reason ) || ! empty( $error_reason ) ) {
```
Comment (Rahmon) [inline includes/classes/Command.php:1062]: @felipeelia this should check the `$error_type`, right?

File: includes/classes/Command.php [hunk 2]
```diff
@@ -1048,15 +1048,20 @@ private function output_index_errors( $errors, Indexable $indexable, $output = t
...
+				$error_text .= '[' . $error_reason . '] ' . $error_reason . "\r\n";
```
Comment (Rahmon) [inline includes/classes/Command.php:1063]: Seems it needs to be fixed either

**Review by Rahmon — APPROVED** [review]

**Review by Rahmon — APPROVED** [review]
