### PR TITLE
Apply ngram_fields on search query when ajax and weighting enable

### LINKED ISSUE #3832: BUG: Inconsistent search results when calling the same function via PHP and Ajax
### Describe the bug

We came across an issue where calling the same function via PHP and AJAX resulted in different results. This only happens when the "Autosuggest" feature is activated.

So further investigation revealed that Autosuggest only adds the `ngram` field to public request https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Autosuggest/Autosuggest.php#L213

We need to pass the `ajax` as a type in `is_integrated_request` function. So the ngram field would also be added for the ajax request.  

### Steps to Reproduce

1. Add `add_filter( 'ep_ajax_wp_query_integration', '__return_true' );` and `add_filter( 'ep_enable_do_weighting', '__return_true' );`
2. Call the function on page load and same function via the ajax call
3. Compare the query body

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress and ElasticPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by burhandodhy**
### Description of the Change

This PR adds the ngram fields to query when ajax integration and weighting is enabled. 

Closes #3832 

### Changelog Entry

> Fixed - Inconsistent search results when calling the same function via PHP and Ajax

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/classes/Feature/Autosuggest/Autosuggest.php [hunk 1]
```diff
@@ -195,7 +195,7 @@ public function set_fuzziness( $fuzziness, $search_fields, $args ) {
 	 * @return array $query adjusted ES Query arguments
 	 */
 	public function adjust_fuzzy_fields( $query, $post_type, $args ) {
-		if ( ! Utils\is_integrated_request( $this->slug, [ 'public' ] ) || empty( $args['s'] ) ) {
+		if ( ! Utils\is_integrated_request( $this->slug, [ 'public', 'ajax' ] ) || empty( $args['s'] ) ) {
```
Comment (felipeelia) [inline includes/classes/Feature/Autosuggest/Autosuggest.php]: @burhandodhy looking at this and the `set_fuzziness` method, I think this could be a breaking change hard to work around. Can we create a new `get_contexts` method that would return `[ 'public', 'ajax' ]` by default, but people could use a filter to change it however they want?

**Review by felipeelia — CHANGES_REQUESTED** [review]

**Review by felipeelia — APPROVED** [review]
