### PR TITLE
Swap filter bool functions

### LINKED ISSUE #3199: BUG: Evaluate other assoc_args as booleans
### Describe the bug

With #3185 we can validate values strictly. There are other areas of improvement to implement this for example:

	public function get_last_cli_sync( $args, $assoc_args ) {

		$last_sync = Utils\get_option( 'ep_last_cli_index', array() );

		if ( isset( $assoc_args['clear'] ) ) {
			Utils\delete_option( 'ep_last_cli_index' );
		}

		$this->pretty_json_encode( $last_sync, $this->filter_boolean( $assoc_args['pretty'] ) );
	}

As of now, the original problem we were solving for the pretty flag seems to be true for other scenarios like this. 
		

### Steps to Reproduce

1.- Pass any value to the --clear flag for get-last-cli-sync
2.- It should delete the ep_last_cli_index option

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress and ElasticPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oscarssanchez**
### Description of the Change

Closes #3199

### Changelog Entry

> Changed - Filter command flags using get_flag_value()

### Credits

Props @oscarssanchez , @felipeelia 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: tests/php/bootstrap.php [hunk 1]
```diff
@@ -128,3 +128,4 @@ function skip_translations_api() {
 require_once __DIR__ . '/includes/classes/FeatureTest.php';
 require_once __DIR__ . '/includes/classes/mock/class-wp-cli-command.php';
 require_once __DIR__ . '/includes/classes/mock/class-wp-cli.php';
+require_once __DIR__ . '/includes/wp-cli-utils.php';
```
Comment (felipeelia) [inline tests/php/bootstrap.php:131]: @oscarssanchez any reason why this class is not in the same folder as the others?
