### PR TITLE
Exclude meta with empty post meta keys

### LINKED ISSUE #3470: BUG: indexing  a post with empty post meta key
### Describe the bug

If you have a post with an empty post meta key, the generated JSON for Elastic to consume will not be compatible, and as a result you'll get `Warning: (Post): [mapper_parsing_exception] failed to parse`

### Steps to Reproduce

1.- Create a post
2.- Create empty post meta key/value for the post
3.- Attempt to index
4.- Indexing will skip the post with the warning `Warning: (Post): [mapper_parsing_exception] failed to parse`

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress and ElasticPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MARQAS**
### Description of the Change
This PR will exclude the post meta with empty or NULL meta keys

Closes #3470 

### How to test the Change
- Create a post
- Add empty post meta to it via code.
- Run the sync
- Notice that the sync will be successful

### Changelog Entry

> Fixed - indexing a post with empty post meta key

### Credits

Props @MARQAS 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: tests/php/indexables/TestPost.php [hunk 1]
```diff
@@ -3886,6 +3886,45 @@ public function filter_ep_prepare_meta_excluded_public_keys( $meta_keys ) {
...
+		$row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM $wpdb->postmeta WHERE meta_key=%s AND post_id = %d", $meta_key, $post_id ) );
+
+		$this->assertSame( $meta_key, $row->meta_key );
+		$this->assertSame( $meta_value_1, $row->meta_value );
+
+		$meta_data = ElasticPress\Indexables::factory()->get( 'post' )->prepare_meta( $post );
+
+		$this->assertTrue( is_array( $meta_data ) && 1 === count( $meta_data ) );
+		$this->assertTrue( is_array( $meta_data ) && array_key_exists( 'test_meta_1', $meta_data ) );
+
```
Comment (felipeelia) [inline tests/php/indexables/TestPost.php]: @MARQAS let's keep tests simple here and check each thing isolated. Also, if a test fails it will stop the whole test, so you just need to check if it is an array once.

ps.: let's also remove the last empty line here :)

**Review by felipeelia — CHANGES_REQUESTED** [review]
