### PR TITLE
Limit users to the current site

### LINKED ISSUE #2599: BUG: User search request yields users who do not exist in the current site
**Describe the bug**
When searching for users, the ElasticPress query may yield users who do not exist in the current site.

This is not obvious by default, but when using some more involved configuration, for example, using autosuggest/ngram.

**Steps to Reproduce**

1. Have a multisite installation.
1. Create a user with login `test`.
1. Do not add that user to any site.
1. On some site, navigate to the Users page, `/wp-admin/users.php`.
1. Search for "test".
1. You will see the user appear as a result. This is wrong!

In order for this to fail, you will need something like the following filter callback running in your site:

```php
add_filter( 'ep_user_formatted_args_query', function ( $query, $args ) {

	$query['bool']['should'][] = [
		'multi_match' => [
			'query' => $args['s'] ?? $args['search'],
			'fields' => [
				'user_login.suggest',
			],
		],
	];

	return $query;
}, 10, 2 );
```

**Expected behavior**

The query should only yield users who exist in the current site.

**Screenshots**

**Environment information**
This bug is independent of the environment.

**Additional context**

### PR DESCRIPTION
**Pull request by felipeelia**
### Description of the Change

This PR is an alternative version of #2601, fixing the problem outlined in #2599 and also preventing an empty `roles` field from being added.

Unit and e2e tests should be added here before merging.

Closes #2599

### Changelog Entry

Fixed: User search results include users who do not exist in the current site.

### Credits

Props @tfrommen and @felipeelia

### CODE REVIEW

File: includes/classes/Indexable/User/User.php [hunk 1]
```diff
@@ -173,6 +173,22 @@ public function format_args( $query_vars, $query ) {
 
 					$use_filters = true;
 				}
+
+				// If there are no specific roles named, make sure the user is a member of the site.
+				if ( ! $use_filters ) {
```
Comment (tfrommen) [inline includes/classes/Indexable/User/User.php:178]: After I submitted my patch (see #2601), I was wondering if relying on `$use_filters` was a good idea. Right now, this works fine, just because there are no conditions that would set `$use_filters` to `true` except for the ones related to roles. However, if there ever was some new code to be added after the inital `$use_filters = false;` and the roles conditions, this would no longer be true.

Instead of checking `$use_filters`, one could do it like so (which is a little more verbose, but absolutely specific to what we're after):

```suggestion
				if ( empty( $query_vars['role'] ) && empty( $query_vars['role__in'] ) && empty( $query_vars['role__not_in'] ) ) {
```

This should work just fine with your tests as well.

Comment (felipeelia) [reply includes/classes/Indexable/User/User.php]: You have a good point @tfrommen. I went ahead and used that to do a small refactor in the entire if block. Hopefully, it'll make the code more future-proof and also easier to be understood by new programmers. Thanks!

**Review by oscarssanchez — APPROVED** [review]
