### PR TITLE
Fix: EP returns nothing when an invalid value is passed to the tax_query field parameter

### LINKED ISSUE #3025: BUG: EP returns nothing when an invalid value is passed to the tax_query field parameter.
**Describe the bug**

By default, the tax_query `field` parameter only accepts `term_id`, `name`, `slug` or `term_taxonomy_id` If any other value passes to `field` parameter, WordPress falls back to default value that is `term_id`. This fallback case is not handled by the EP and, due to that, the EP returns no post for the query. 

**Steps to Reproduce**

1. Run the below snippet  and no post will be return
```
add_action( 'init',function() : void {


	$args = array(
		'ep_integrate' => true,
		'posts_per_page'  => 10,
		'tax_query' => array(
			array(
				'taxonomy' => 'category',
				'field'    => 'id', // invalid field name
				'terms'    => termID, // update the value
			),
		),
	);
	$query = new \WP_Query( $args );
	if ( $query->have_posts() ) : ?>
			<?php while ( $query->have_posts() ) : $query->the_post(); ?>
				<?php the_title(); ?>
			<?php endwhile; ?>
	<?php endif; ?>
	<?php wp_reset_postdata();
}  );

```
2. Set `ep_integrate` to `false` and see WordPress will return the posts

### PR DESCRIPTION
**Pull request by burhandodhy**
### Description of the Change

This PR fixes the issue where the EP returns no post when the invalid value passes to `field` parameter to tax_query. 

Closes #3025 

### How to test the Change

Use the below snippet. It should return the posts

```
add_action( 'init',function() : void {


	$args = array(
		'ep_integrate' => true,
		'posts_per_page'  => 10,
		'tax_query' => array(
			array(
				'taxonomy' => 'category',
				'field'    => 'id', // invalid field name
				'terms'    => termID, // update the value
			),
		),
	);
	$query = new \WP_Query( $args );
	if ( $query->have_posts() ) : ?>
			<?php while ( $query->have_posts() ) : $query->the_post(); ?>
				<?php the_title(); ?>
			<?php endwhile; ?>
	<?php endif; ?>
	<?php wp_reset_postdata();
}  );

```

### Changelog Entry

> Fixed - Returns no posts when an invalid value is passed to the tax_query field parameter

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/classes/Indexable/Post/Post.php [hunk 1]
```diff
@@ -2153,4 +2149,31 @@ public function get_search_algorithm( string $search_text, array $search_fields,
...
+			case 'slug':
+				$field = 'slug';
+				break;
+			case 'term_taxonomy_id':
+				$field = 'term_taxonomy_id';
+				break;
+			default:
+				$field = 'term_id';
+				break;
+		}
```
Comment (felipeelia) [inline includes/classes/Indexable/Post/Post.php]: @burhandodhy instead of a switch, can we go with a "from-to" array, like we now have [here](https://github.com/10up/ElasticPress/blob/993cba781aef2cca5a888e796684121d400a02a7/includes/classes/Indexable/Post/Post.php#L1210)? It seems to be a more readable approach. We would have something like:
```php
	protected function parse_tax_query_field( $field ) : string {
		$from_to = [
			'name'             => 'name.raw',
			'slug'             => 'slug',
			'term_taxonomy_id' => 'term_taxonomy_id',
		];

		return $from_to[ $field ] ?? 'term_id';
	}
```

**Review by felipeelia — CHANGES_REQUESTED** [review]
Just a minor change @burhandodhy (and a git conflict that needs to be fixed.) Thanks!

File: includes/classes/Indexable/Post/Post.php (hunk 1 above)
Comment (burhandodhy) [reply includes/classes/Indexable/Post/Post.php]: Done
