### PR TITLE
BUG FIX: The Field Grouping change should retain old fields values

### LINKED ISSUE #4170: BUG: The Field Grouping change should retain old fields values
### Describe the bug

The field grouping introduced in #4142 has some problems we need to fix ASAP:

- Old values are not migrated to the group
- The field value is stored in a nested way, which would break retrocompatibility

### Steps to Reproduce

Apply the field_group schema to fields in the Vector Embeddings feature in https://github.com/10up/ElasticPressLabs/pull/126

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress and ElasticPress information

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ZacharyRener**
### Description of the Change

Previously, I had set up a new settings schema type: field_group. It was rendering a whole new Control, and nesting the stored values. This would lead to the old values not being retained once moved into a field_group, and didn't have great retrocompatibility.

To address this, I've changed how field_groups work. Now, there is no field_group type. Instead, fields stay flat, but now have a `field_group_slug` and `field_group_label` key/value pair. That keeps things working with retrocompatibility, and retains the old values. Its now the same exact fields: the frontend just renders them in a group visually. This also helped reduced some repetitive logic surrounding conditional fields.

Closes #4170 

### How to test the Change

```
public function set_i18n_strings(): void {
        ...
	$this->field_group_map = [
		'highlight_group' => __( 'Highlight Group', 'elasticpress' ),
	];
        ...
}
```

```
protected function set_settings_schema() {
...
$this->settings_schema = [
	[
		...
		'key'               => 'highlight_enabled',
		'field_group_slug'  => 'highlight_group',
		'field_group_label' => $this->field_group_map['highlight_group'],
	],
	[
			...
		'key'               => 'highlight_excerpt',
		'field_group_slug'  => 'highlight_group',
		'field_group_label' => $this->field_group_map['highlight_group'],
	],
...
```

### Changelog Entry

> Fixed - Field groups weren't retaining old values

### Credits

Props @ZacharyRener 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/classes/Feature/Search/Search.php [hunk 1]
```diff
@@ -894,61 +898,60 @@ protected function set_settings_schema() {
...
-				'key'    => 'highlighting',
-				'label'  => __( 'Highlighting Options', 'elasticpress' ),
-				'fields' => [
+				'default'           => '0',
+				'help'              => __( 'Enable to wrap search terms in HTML tags in results for custom styling. The wrapping HTML tag comes with the <code>ep-highlight</code> class for easy styling.', 'elasticpress' ),
+				'key'               => 'highlight_enabled',
+				'label'             => __( 'Highlight search terms', 'elasticpress' ),
+				'type'              => 'checkbox',
+				'field_group_slug'  => 'highlight_group',
+				'field_group_label' => $this->field_group_map['highlight_group'],
```
Comment (felipeelia) [inline includes/classes/Feature/Search/Search.php]: @ZacharyRener instead of sending the label on all fields, can't we just send the group slug and figure out the label sending the map to JS?

Comment (felipeelia) [reply includes/classes/Feature/Search/Search.php]: Also, it seems the group label is now "Highlight Group" instead of "Highlighting Options"? (I prefer "Highlighting Options" :) )

Comment (ZacharyRener) [reply includes/classes/Feature/Search/Search.php]: Sure, moved the map to JS

Comment (ZacharyRener) [reply includes/classes/Feature/Search/Search.php]: Moved to Feature abstract class + changed back to Highlighting Options

File: includes/classes/Feature.php [hunk 2]
```diff
@@ -640,4 +641,27 @@ protected function set_settings_schema() {
...
+	 *
+	 * @since 5.3.0
+	 * @return array
+	 */
+	public function get_field_group_map(): array {
+		$field_groups = [
+			'highlight_group' => [
+				'label' => esc_html__( 'Highlighting Options', 'elasticpress' ),
+			],
+		];
```
Comment (felipeelia) [inline includes/classes/Feature.php]: @ZacharyRener This does not belong to the abstract class; it is something super specific to the Search Feature class. You can either override the method there or use the new ep_feature_field_groups field.

**Review by felipeelia — CHANGES_REQUESTED** [review]
@ZacharyRener in addition to the comment I left, it seems Unit tests are not passing as well.

File: includes/classes/Feature.php (hunk 2 above)
Comment (ZacharyRener) [reply includes/classes/Feature.php]: Adjusted
