### PR TITLE
Load full status report on demand with Ajax

### LINKED ISSUE #3767: BUG: EP status page page=elasticpress-status-report is very slow (18s+) due to multiple huge "Distinct Meta Keys" queries
### Describe the bug

Whenever we load the EP status page /wordpress/wp-admin/admin.php?page=elasticpress-status-report, it takes 18-20s. I finally installed Query Monitor and it showed that this page runs 32 (currently) humongous queries like this:

```
SELECT DISTINCT meta_key
FROM wp_postmeta
WHERE post_id IN ( 642170,642211,642481,643012,643084,643098,643128,643348,643567,644581,645503,645518,645616,645655,645805,646050,646069,646184,646657,646727,646833,647514,647765,647900,647912,647924,647927,647969,647978,648409,648629,648632,648658,648664,648780,648867,649360,649363,649389,649392, ..., 1879856,1879890,1879921,1879941,1880037,1880040,1880145,1880229,1880308,1880326,1880447,1880454,1880602,1880718,1880737 )
```
each taking just under 1 second. It looks like it's batching IDs in batches of 10100 (weird number, but OK) and doing 32 queries. Presumably, all to populate this field "Distinct Meta Keys"?

There has to be a better way to do this? Maybe load this information via Ajax on demand or optimize the queries so that they run faster and perhaps without listing hundreds of thousands of post IDs?

### Steps to Reproduce

1. Load /wordpress/wp-admin/admin.php?page=elasticpress-status-report on a large site.

### Screenshots, screen recording, code snippet

image
image

### Environment information

_No response_

### WordPress and ElasticPress information

Partially redacted.

### WordPress Environment ###
wp_version: 6.4.1
is_multisite: false
revisions: 15

### Server Environment ###
php_version: 7.4.33
memory_limit: 1G
timeout: 600

### XXXXXXXXXXXXX — https://www.XXXXXXXXXXXXX.com/wordpress ###
post_count: 0
page_count: 9
XXXXXXXXXXXXX: 877,888
XXXXXXXXXXXXX: 1,441,662
XXXXXXXXXXXXX: 565,659
attachment_count: 154,949
XXXXXXXXXXXXX: 23
XXXXXXXXXXXXX: 15
XXXXXXXXXXXXX: 14
total-all-post-types: 25
distinct-meta-keys: XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXXXXX, and XXXXXXXXXXXXX

### Settings ###
host: http://XXXXXXXXXXXXX:9200
index_prefix: 
language: en_US
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30

### XXXXXXXXXXXXX ###
health: green
status: open
index: XXXXXXXXXXXXX
uuid: XXXXXXXXXXXXX
pri: 20
rep: 3
docs.count: 3040168
docs.deleted: 405218
store.size: 28.2gb
pri.store.size: 7gb
total_fields_limit: 5000

### 2023/08/02 6:22:57 pm ###
method: WP Dashboard
end_date_time: 2023/08/09 3:55:23 am
total_time: 9 hours, 32 minutes, 27 seconds
total: 3388535
synced: 3410235
skipped: 0
failed: 0
errors: array (
)

### Custom Search Results ###
active: true
force_inactive: false

### Facets ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: true
force_inactive: false
highlight_enabled: false
highlight_excerpt: false
highlight_tag: mark
synonyms_editor_mode: simple

### Protected Content ###
active: true
force_inactive: false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oscarssanchezz**
### Description of the Change

This PR adds functionality to load resource intensive reports on demand with a "Generate Full Status Report" button. 

If the full status report has not been generated yet, it should show a warning message declared by the specific report, prompting users to generate the full status report to see it.

If the status report has not been generated yet, copy to clipboard and download status report buttons should not be available, as these will contain an incomplete status report. 

https://github.com/user-attachments/assets/a678812d-a610-4d56-8ff5-2356896522f8

Closes #3767

### How to test the Change

1.- Open Status Report page.
2.- Check the status reports that should be loaded with ajax are showing the correct notice (only indexables at this point).
3.- Download status report and copy to clipboard buttons should be disabled.
4.- Click on Generate Full status report.
5.- Report should now show all groups and notice should be gone.
6.- Download status report and copy to clipboard should have full Info. 
7.- Generate Full status report button should be disabled.

### Changelog Entry

> Changed - Potentially resource intensive status reports are loaded on demand with AJAX.

### Credits

Props @oscarssanchez , @felipeelia

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: assets/js/status-report/components/reports/report.js [hunk 1]
```diff
@@ -1,15 +1,14 @@
...
-import { safeHTML } from '@wordpress/dom';
-import { RawHTML, WPElement } from '@wordpress/element';
-import { decodeEntities } from '@wordpress/html-entities';
+import { WPElement } from '@wordpress/element';
 
 /**
  * Internal dependencies.
  */
-import Value from './report/value';
+// import ReportHeader from './report/header';
```
Comment (felipeelia) [inline assets/js/status-report/components/reports/report.js]: I guess this was a left-over and can be removed?

File: includes/classes/Screen/StatusReport.php [hunk 2]
```diff
@@ -82,6 +88,35 @@ public function admin_enqueue_scripts() {
...
+		}
+
+		$post = wp_unslash( $_POST );
+
+		if ( empty( $this->formatted_reports ) ) {
+			$this->formatted_reports = $this->get_reports();
+		}
+
+		if ( empty( $this->formatted_reports[ $post['report'] ] ) ) {
+			wp_send_json_error( [ 'message' => 'Report not found.' ], 404 );
```
Comment (felipeelia) [inline includes/classes/Screen/StatusReport.php]: This string needs to be translatable, no?

File: includes/classes/Screen/StatusReport.php [hunk 3]
```diff
@@ -147,10 +183,11 @@ protected function get_formatted_reports(): array {
...
 					return [
-						'actions'  => $report->get_actions(),
-						'groups'   => $report->get_groups(),
-						'messages' => $report->get_messages(),
-						'title'    => $report->get_title(),
+						'actions'        => $report->get_actions(),
+						'groups'         => ! $report->is_ajax_report() ? $report->get_groups() : [],
+						'messages'       => $report->get_messages(),
+						'title'          => $report->get_title(),
+						'is_ajax_report' => $report->is_ajax_report(),
```
Comment (felipeelia) [inline includes/classes/Screen/StatusReport.php]: for variables we are passing to JS, we are using camelCase, so this will need to be isAjaxReport.

**Review by felipeelia — CHANGES_REQUESTED** [review]
In addition to my comments, @oscarssanchezz:

1. This needs both unit and e2e tests;
2. It seems the "Indexable Content" information is not present if you download or copy the report
3. Did you explore breaking ajax reports into separate requests? Right now, we only have one report that relies on ajax, but if we need another in the future, wouldn't it be better if we could fire multiple (parallel) ajax requests instead of a giant single request?
4. I'm a bit concerned with the UX here. Shouldn't we allow people to download a partial report?

File: assets/js/status-report/components/reports.js [hunk 4]
```diff
@@ -23,58 +23,190 @@ import '../style.css';
...
+
+		createNotice('info', __('Successfully generated status report.', 'elasticpress'));
+	};
 
 	return (
 		<>
 			<p>
 				{__(
-					'This screen provides a list of information related to ElasticPress and synced content that can be helpful during troubleshooting. This list can also be copy/pasted and shared as needed.',
+					'This screen provides a list of information related to ElasticPress and synced content that can be helpful during troubleshooting. As the process can be resource-intensive, you must click the "Generate Full Status Report" button to generate a full report list. Once generated, this list can also be copy/pasted and shared as needed.',
```
Comment (felipeelia) [inline assets/js/status-report/components/reports.js]: Should we update this, now that people can generate (and copy/paste) partial reports?

File: includes/classes/Screen/StatusReport.php [hunk 5]
```diff
@@ -82,6 +83,70 @@ public function admin_enqueue_scripts() {
 		);
 	}
 
+	/**
+	 * AJAX action to load an individual report group.
+	 */
```
Comment (felipeelia) [inline includes/classes/Screen/StatusReport.php]: Let's add a `@since` tag here, please.

File: includes/classes/Screen/StatusReport.php [hunk 6]
```diff
@@ -82,6 +83,70 @@ public function admin_enqueue_scripts() {
...
+		);
+	}
+
+	/**
+	 * Get single report by slug in AJAX context.
+	 *
+	 * @param string $report_slug Report slug
+	 * @return \ElasticPress\StatusReport\AjaxReport|\WP_Error
+	 */
+	public function get_single_report( $report_slug ): \ElasticPress\StatusReport\Report|\WP_Error {
```
Comment (felipeelia) [inline includes/classes/Screen/StatusReport.php]: Do you mind explaining why we need a new method to get reports, instead of using get_reports?

File: includes/classes/StatusReport/AjaxReport.php [hunk 7]
```diff
@@ -0,0 +1,33 @@
+<?php
+/**
+ * AjaxReport abstract class
+ *
+ * @package elasticpress
```
Comment (felipeelia) [inline includes/classes/StatusReport/AjaxReport.php:5]: Let's add a `@since` tag here, please

File: tests/cypress/integration/status-report.cy.js
Comment (felipeelia) [inline tests/cypress/integration/status-report.cy.js:1]: Different from unit tests, e2e tests should contain as much as we can in a single test, as the overhead of starting a new test is quite large. Do you mind changing this to check all those (or at least as much as we can) in bigger tests?

File: tests/php/screen/TestStatusReport.php [hunk 8]
```diff
@@ -499,4 +500,106 @@ public function testElasticPressReport() {
 		$this->assertSame( $expected_result, $report->get_groups() );
 		$this->assertEquals( 2, count( $groups ) );
 	}
+
+	/**
+	 * Test that a single report with valid slug.
+	 *
+	 * @group statusReport
+	 */
```
Comment (felipeelia) [inline tests/php/screen/TestStatusReport.php]: All these new tests will need `@since` tags as well.

File: includes/classes/StatusReport/IndexableContent.php [hunk 9]
```diff
@@ -191,4 +191,26 @@ protected function get_post_meta_fields(): array {
 
 		return $fields;
 	}
+
+	/**
+	 * Return the report messages.
+	 *
+	 * @return array
+	 */
+	public function get_messages(): array {
```
Comment (felipeelia) [inline includes/classes/StatusReport/IndexableContent.php]: What do you think about moving this method (as is) to the parent class? Other implementations of AjaxReport will likely have identical messages.

**Review by felipeelia — CHANGES_REQUESTED** [review]

File: includes/classes/Screen/StatusReport.php (hunk 6 above)
Comment (oscarssanchezz) [reply includes/classes/Screen/StatusReport.php]: The rationale is to prevent instantiation of reports that we do not need here:

```
		$reports['wordpress']    = new \ElasticPress\StatusReport\WordPress();
		$reports['indexable']    = new \ElasticPress\StatusReport\IndexableContent();
		$reports['elasticpress'] = new \ElasticPress\StatusReport\ElasticPress();
		$reports['indices']      = new \ElasticPress\StatusReport\Indices();
		$reports['last-sync']    = new \ElasticPress\StatusReport\LastSync();
		$reports['features']     = new \ElasticPress\StatusReport\Features();
```
It can be rolled back if needed to use get_reports()

File: assets/js/status-report/components/reports.js (hunk 4 above)
Comment (oscarssanchezz) [reply assets/js/status-report/components/reports.js]: Updated message https://github.com/10up/ElasticPress/pull/4095/commits/431100a25b76e9163eb100170a2189692ead9e55

File: includes/classes/StatusReport/AjaxReport.php (hunk 7 above)
Comment (oscarssanchezz) [reply includes/classes/StatusReport/AjaxReport.php:5]: added here https://github.com/10up/ElasticPress/pull/4095/commits/68e26d78a7db31b8cc16128280e3d1047651f4f8

File: tests/php/screen/TestStatusReport.php (hunk 8 above)
Comment (oscarssanchezz) [reply tests/php/screen/TestStatusReport.php]: added here https://github.com/10up/ElasticPress/pull/4095/commits/68e26d78a7db31b8cc16128280e3d1047651f4f8

File: includes/classes/StatusReport/IndexableContent.php (hunk 9 above)
Comment (oscarssanchezz) [reply includes/classes/StatusReport/IndexableContent.php]: Moved to parent class https://github.com/10up/ElasticPress/pull/4095/commits/f7ea342a6e30cc8030866302979b7213f443c871

File: tests/cypress/integration/status-report.cy.js
Comment (oscarssanchezz) [reply tests/cypress/integration/status-report.cy.js:1]: Consolidated here: https://github.com/10up/ElasticPress/pull/4095/commits/ab4ab5ed09ca93087ae8d26cfff691b33988376e

File: includes/classes/Screen/StatusReport.php (hunk 6 above)
Comment (felipeelia) [reply includes/classes/Screen/StatusReport.php]: That is a valid point, but it seems the classes' instantiation doesn't add much overhead (we don't do anything on their __construct() method, as far as I can see). In addition to that, get_reports allows new reports to be added (through that ep_status_report_reports filter), which doesn't happen here.

Comment (oscarssanchezz) [reply includes/classes/Screen/StatusReport.php]: Makes sense, changed it here [Remove get_single_report](https://github.com/10up/ElasticPress/pull/4095/commits/7264e3fc65bf310d9d9aa4772923b4d0a95c3293)
