### PR TITLE
Add Tests for Search highlight & Fix issue where EP returns incorrect excerpt

### LINKED ISSUE #3101: BUG: Incorrect excerpt when Excerpt highlighting is enabled
**Describe the bug**

When the `Excerpt highlighting` is enabled, we call the `get_the_excerpt` function outside of the loop for the different post. It returns the excerpt of the post of main loop. This happened because [get_the_content](https://github.com/10up/ElasticPress/blob/burhan/unit-test-for-highlight-search/includes/classes/Feature/Search/Search.php#L293) is looking for the content of main loop post.

**Steps to Reproduce**

1. Enable `Excerpt highlighting` option
2. Create a post and leave the excerpt empty
3. Search for that post through the code.
```
	$posts = get_posts( [ 's' => 'searchTerm' ] );
	var_dump( get_the_excerpt( $post[0] ) );
```
4. Returns the excerpt of different post. 

**Expected behavior**

Should return the excerpt of correct post.

**Additional context**

### PR DESCRIPTION
**Pull request by burhandodhy**
### Description of the Change

This PR fixes the issue where EP returns the incorrect excerpt when the `Excerpt highlighting` option is enabled and `get_the_excerpt` is called without the Post Loop. 

Closes #3101 

### How to test the Change

1. Enable Excerpt highlighting option
2. Create a post and leave the excerpt empty
3. Search for that post through the code.

```
        $posts = get_posts( [ 's' => 'searchTerm' ] );
	var_dump( get_the_excerpt( $post[0] ) );
```

### Changelog Entry

> Fixed - Incorrect Excerpt when `get_the_excerpt` is called without Loop and `Excerpt highlighting` option is enabled

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/classes/Feature/Search/Search.php [hunk 1]
```diff
@@ -275,10 +275,12 @@ public function allow_excerpt_html() {
 	 * Called by allow_excerpt_html
 	 * logic for the excerpt filter allowing the currently selected tag.
 	 *
-	 * @param string $text - excerpt string
+	 * @param string  $text - excerpt string
+	 * @param WP_POST $post - Post Object.
+	 *
```
Comment (felipeelia) [inline includes/classes/Feature/Search/Search.php]: @burhandodhy can we please make it WP_Post instead of WP_POST and remove the `-` between the variable and its description?

**Review by felipeelia — CHANGES_REQUESTED** [review]

File: includes/classes/Feature/Search/Search.php (hunk 1 above)
Comment (burhandodhy) [reply includes/classes/Feature/Search/Search.php]: Done
