### PR TITLE
Fix Synonyms case sensitive issue

### LINKED ISSUE #3855: BUG: Synonyms are case sensitive
### Describe the bug

Currently, the synonyms are case-sensitive. It will not give the right result if the words do not exactly match.

### Steps to Reproduce

1. Create a synonym alternative set for “hoodie” and "sweatshirt.”
2. Search for the Hoodie on the frontend. 

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress and ElasticPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by burhandodhy**
### Description of the Change

This PR fixes an issue where search synonyms are case sensitive

Closes #3855 

### Changelog Entry

> Fixed - Fix Synonyms case sensitive issue

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/classes/Feature/Search/Synonyms.php [hunk 1]
```diff
@@ -823,4 +827,23 @@ private function update_synonym_post( $content ) {
...
 	}
+
+	/**
+	 * Change the position of the lowercase filter to the beginning of the array.
+	 *
+	 * @param array $filters Array of filters.
+	 *
+	 * @return array
+	 */
+	private function maybe_change_filter_position( $filters ) {
```
Comment (felipeelia) [inline includes/classes/Feature/Search/Synonyms.php]:
```suggestion
	/**
	 * Change the position of the lowercase filter to the beginning of the array.
	 *
	 * @since 5.1.0
	 * @param array $filters Array of filters.
	 * @return array
	 */
	protected function maybe_change_filter_position( array $filters ) : array {
```

**Review by felipeelia — CHANGES_REQUESTED** [review]
