### PR TITLE
Assumption safety checks for queried object

### LINKED ISSUE #3331: BUG: EP crashes trying to use queried object that doesn't exist
### Describe the bug

This code in `includes/classes/Indexable/Post/QueryIntegration.php` assumes that `$query->get_queried_object()` always returns a term, this is not a safe assumption:

```php
		if ( empty( $query_vars['post_type'] ) ) {
			if ( $query->is_tax() ) {
				$query_vars['post_type'] = get_taxonomy( $query->get_queried_object()->taxonomy )->object_type;
			} elseif ( empty( $query_vars['s'] ) ) {
```

### Steps to Reproduce

Not 100% on the steps that lead to this, only that this is what I got at the other end

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress and ElasticPress information

latest version of elasticpress 4.4.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ZacharyRener**
### Description of the Change

Closes #3331 

### Changelog Entry

> Fixed - Error when trying to use queried object that doesn't exist

### Credits

Props @tomjn @ZacharyRener 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/classes/Indexable/Post/QueryIntegration.php [hunk 1]
```diff
@@ -243,11 +243,13 @@ public function get_es_posts( $posts, $query ) {
 		}
 
 		/**
-		 * If not search and not set default to post. If not set and is search, use searchable post types
+		 * If not search and not set default to post. If not set and is search, use searchable post types.
```
Comment (felipeelia) [inline includes/classes/Indexable/Post/QueryIntegration.php]:
```suggestion
		 * If not search and not set, default to post. If not set and is search, use searchable post types.
```

File: includes/utils.php [hunk 2]
```diff
@@ -930,3 +930,34 @@ function is_top_level_admin_context() {
...
+ * Safely resolve the post type(s) for a taxonomy query.
+ *
+ * Guards against null queried objects, missing taxonomy properties,
+ * and deregistered taxonomies that would otherwise cause fatal errors
+ * when chaining get_queried_object()->taxonomy through get_taxonomy().
+ *
+ * Returns null when the query is not a taxonomy query, allowing callers
+ * to distinguish "not a tax query" from "tax query that failed to resolve."
+ *
+ * @since 5.3.0
```
Comment (felipeelia) [inline includes/utils.php]:
```suggestion
 * @since 5.3.3
```

**Review by felipeelia — CHANGES_REQUESTED** [review]

File: includes/utils.php [hunk 3]
```diff
@@ -930,3 +930,34 @@ function is_top_level_admin_context() {
...
+ *
+ * @param \WP_Query|null $query Optional. WP_Query instance. Defaults to the global query.
+ * @return array|null Post type array on success, null otherwise.
+ */
+function get_post_type_for_tax_query( $query = null ) {
```
Comment (tomjn) [inline includes/utils.php]: We could type hint this as `?WP_Query`, this does mean that we would need to enforce a minimum PHP version of ...... v7.1

Comment (tomjn) [reply includes/utils.php]: likewise a return type could be added of `?array`

Comment (tomjn) [reply includes/utils.php]: and since this is returning an array of types plural, should it be renamed to `get_post_types_for_tax_query`?

File: includes/utils.php [hunk 4]
```diff
@@ -930,3 +930,34 @@ function is_top_level_admin_context() {
...
+	}
+
+	$queried_object = $query instanceof \WP_Query ? $query->get_queried_object() : get_queried_object();
+	if ( ! $queried_object || ! isset( $queried_object->taxonomy ) ) {
+		return null;
+	}
+
+	$taxonomy_object = get_taxonomy( $queried_object->taxonomy );
+
+	return $taxonomy_object ? $taxonomy_object->object_type : null;
```
Comment (tomjn) [inline includes/utils.php]: While `object_type` can be null, it can also be a value that is not a post type, e.g. a comments or users. While less common, a user taxonomy would lead to it trying to work with a `user` CPT so there's some validation needed.

Comment (tomjn) [reply includes/utils.php]: Also what's the difference between returning `null` and returning `[]`? Could it just return an empty array and skip the whole `null` thing?

File: includes/utils.php [hunk 5]
```diff
@@ -930,3 +930,34 @@ function is_top_level_admin_context() {
...
+ * @param \WP_Query|null $query Optional. WP_Query instance. Defaults to the global query.
+ * @return array|null Post type array on success, null otherwise.
+ */
+function get_post_type_for_tax_query( $query = null ) {
+	$is_tax = $query instanceof \WP_Query ? $query->is_tax() : is_tax();
+	if ( ! $is_tax ) {
+		return null;
+	}
+
+	$queried_object = $query instanceof \WP_Query ? $query->get_queried_object() : get_queried_object();
```
Comment (tomjn) [inline includes/utils.php]: these ternaries could be avoided with a guard that assigns `$query` the value of the `$wp_query` global if it is null

**Comment by ZacharyRener** [comment]
@tomjn Points addressed with latest push.

**Review by tomjn — APPROVED** [review]

File: includes/utils.php [hunk 6]
```diff
@@ -930,3 +930,39 @@ function is_top_level_admin_context() {
...
+ *
+ * @param \WP_Query|null $query Optional. WP_Query instance. Defaults to the global query.
+ * @return array Registered post type names on success, empty array otherwise.
+ */
+function get_post_types_for_tax_query( ?\WP_Query $query = null ): array {
+	if ( null === $query ) {
+		global $wp_query;
+		$query = $wp_query;
+	}
+
```
Comment (felipeelia) [inline includes/utils.php:953]:
```suggestion
	global $wp_query;

	if ( null === $query ) {
		$query = $wp_query;
	}

```

**Review by felipeelia — CHANGES_REQUESTED** [review]
