### PR TITLE
Fix: Use 'ep_' . $indexable->slug . '_sync_kill' to prevent indexing the object

### LINKED ISSUE #4278: BUG: Inconsistency in checks for skipping index between bulk index and individual index
### Describe the bug

When using a general `ep_item_sync_kill` filter to exclude certain items from being indexed:

- The filter correctly prevents items matching the criteria from being indexed during a bulk index.
- However, the filter does not prevent these items from being indexed when they are updated individually.

I would expect that the is_post_indexable function in https://github.com/10up/ElasticPress/blob/5.3.2/includes/classes/Indexable/Post/SyncManager.php#L810 would both run the ep_item_sync_kill AND ep_post_sync_kill filters as it does in the bulk command

### Steps to Reproduce

1. Configure an ep_item_sync_kill filter.
2. Update a post in the CMS that matches the ep_item_sync_kill filter criteria.
3. Observe that the post is unexpectedly indexed in Elasticsearch.

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress Environment ###
wp_version: 6.9
home_url: http://localhost
site_url: http://localhost/wp
is_multisite: true
theme: Acme (11.0.1)
plugins: Advanced Custom Fields PRO (6.5.0.1), ElasticPress (5.3.2), Gravity Forms (2.9.15.2), Polylang for WooCommerce (2.1.4), Polylang Pro (3.7.3), Rank Math SEO (1.0.262), WooCommerce (10.4.3), WP Crontrol (1.20.0), and WP Mail SMTP (4.7.1)
revisions: 3

### Server Environment ###
php_version: 8.3.29
memory_limit: 512M
timeout: 30

### Localhost &mdash; http://localhost/wp ###
post_count: 1
page_count: 57
product_count: 20
faq_count: 0
vacancy_count: 6
blog_count: 2
news_count: 2
innovation_count: 26
event_count: 2
attribute_group_count: 6
attribute_unit_count: 14
solution_count: 2
post_meta_keys: 0
page_meta_keys: 0
product_meta_keys: 0
faq_meta_keys: 0
vacancy_meta_keys: 0
blog_meta_keys: 0
news_meta_keys: 0
innovation_meta_keys: 0
event_meta_keys: 0
attribute_group_meta_keys: 0
attribute_unit_meta_keys: 0
solution_meta_keys: 0
total-all-post-types: 0
distinct-meta-keys: 

### Settings ###
host: http://opensearch:9200
index_prefix: 
language: site-default
per_page: 350
network_active: false

### Timeouts ###
request_timeout: 30
index_document_timeout: 15
bulk_request_timeout: 30

### localhostwp-post-1 ###
health: yellow
status: open
index: localhostwp-post-1
uuid: aOArLL3vTpmKwQVuSJk-KA
pri: 5
rep: 1
docs.count: 19
docs.deleted: 0
store.size: 1.2mb
pri.store.size: 1.2mb
total_fields_limit: 9000
analyzer_language: english
stop_language: _english_
snowball_language: English

### 2026/01/30 11:55:47 am ###
method: WP-CLI
is_full_sync: Yes
end_date_time: 2026/01/30 11:55:52 am
total_time: 0 hours, 0 minutes, 6 seconds
total: 20
synced: 20
skipped: 0
failed: 0
errors: array (
)
trigger: 
final_status: success

### ACF Repeater Field ###
active: true
force_inactive: false

### Autosuggest ###
active: true
autosuggest_selector: .search-input-modal
endpoint_url: http://localhost/wp-json/opensearch-proxy/search
force_inactive: false
trigger_ga_event: 0

### Custom Search Results ###
active: true
force_inactive: false

### Filters ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: 0
highlight_excerpt: 0
highlight_tag: mark
synonyms_editor_mode: simple
synonyms: <pre># Defined synonyms.
runner, running shoe, sneaker, tennis shoe, trainer

# Defined hyponyms.
blue => blue, aqua, azure, cerulean, cyan, ultramarine

# Defined replacements.
supposably => supposedly
flustrated => flustered, frustrated
intensive purposes => intents and purposes</pre>
weighting: array (
)

### Related Posts ###
active: true
force_inactive: false

### WooCommerce ###
active: true
force_inactive: false
orders: 0

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by burhandodhy**
### Description of the Change

This PR ensures that using `ep_' . $indexable->slug . '_sync_kill` is sufficient to prevent the object from being indexed, either through sync or post update.

Closes #4278 

### Changelog Entry

> Developer - : Ensure ep_{$indexable->slug}_sync_kill properly prevents object indexing during sync and post updates.
### Credits

Props @burhandodhy @felipeelia @matthijsch

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/classes/Feature/WooCommerce/OrdersAutosuggest.php [hunk 1]
```diff
@@ -566,6 +568,22 @@ public function add_settings_schema( array $settings_schema ): array {
...
 
+	/**
+	 * Short-circuit the sync for password protected orders.
+	 *
+	 * @param null|bool $new_skip Short-circuit flag
+	 * @param bool      $skip     Current value of $skip
+	 * @param int       $object_id The object ID
+	 * @return null|bool
+	 */
+	public function sync_password_protected_orders( $new_skip, bool $skip, $object_id ) {
```
Comment (felipeelia) [inline includes/classes/Feature/WooCommerce/OrdersAutosuggest.php]: @burhandodhy let's avoid forcing types on methods hooked into actions and filters, as this has caused us some problems lately. We can certainly cast it to bool on return though.

File: includes/classes/IndexHelper.php [hunk 2]
```diff
@@ -1178,24 +1178,46 @@ protected function should_skip_object_index( $indexable_object, $indexable ) {
...
+		 * Conditionally kill indexing for an object
 		 *
+		 * @deprecated 5.3.3 Use ep_{indexable_slug}_sync_kill instead
 		 * @hook ep_{indexable_slug}_index_kill
 		 * @param  {bool} $index True means dont index
 		 * @param  {int} $object_id Object ID
 		 * @return {bool} New value
 		 */
-		$ep_indexable_sync_kill = apply_filters( 'ep_' . $indexable->slug . '_index_kill', false, $indexable_object->ID );
+		$ep_indexable_index_kill = apply_filters_deprecated(
```
Comment (felipeelia) [inline includes/classes/IndexHelper.php:1195]: We can remove the docblock of this filter and simply state that it is documented in that other file.

File: includes/classes/IndexHelper.php [hunk 3]
```diff
@@ -1178,24 +1178,46 @@ protected function should_skip_object_index( $indexable_object, $indexable ) {
...
+
+		/**
+		 * Conditionally kill indexing for an object
+		 *
+		 * @hook ep_{indexable_slug}_sync_kill
+		 * @param  {bool} $kill True means dont sync
+		 * @param  {int} $object_id Object ID
+		 * @return {bool} New value
+		 */
+		$ep_indexable_sync_kill = apply_filters( 'ep_' . $indexable->slug . '_sync_kill', false, $indexable_object->ID );
```
Comment (felipeelia) [inline includes/classes/IndexHelper.php:1203]: same here

**Review by felipeelia — CHANGES_REQUESTED** [review]

File: includes/classes/Feature/WooCommerce/OrdersAutosuggest.php [hunk 4]
```diff
@@ -566,6 +568,22 @@ public function add_settings_schema( array $settings_schema ): array {
...
 
+	/**
+	 * Short-circuit the sync for password protected orders.
+	 *
+	 * @param null|bool $new_skip Short-circuit flag
+	 * @param bool      $skip     Current value of $skip
+	 * @param int       $object_id The object ID
+	 * @return null|bool
+	 */
+	public function sync_password_protected_orders( $new_skip, $skip, $object_id ) {
```
Comment (felipeelia) [inline includes/classes/Feature/WooCommerce/OrdersAutosuggest.php:580]:
```suggestion
	/**
	 * Short-circuit the sync for password protected orders.
	 *
	 * @since 5.3.3
	 * @param null|bool $new_skip Short-circuit flag
	 * @param bool      $skip     Current value of $skip
	 * @param int       $object_id The object ID
	 * @return null|bool
	 */
	public function sync_password_protected_orders( $new_skip, $skip, $object_id ) {
```

File: includes/classes/Indexable.php [hunk 5]
```diff
@@ -279,13 +279,27 @@ public function index( $object_id, $blocking = false ) {
...
 		 *
+		 * @deprecated 5.3.3 Use ep_{indexable_slug}_sync_kill instead
 		 * @hook ep_{indexable_slug}_index_kill
 		 * @param  {bool} $kill True to not index
 		 * @param {int} $object_id Id of object to index
 		 * @since  3.0
 		 * @return {bool}  New kill value
 		 */
-		if ( apply_filters( 'ep_' . $this->slug . '_index_kill', false, $object_id ) ) {
+		if ( apply_filters_deprecated( 'ep_' . $this->slug . '_index_kill', [ false, $object_id ], '5.3.3', 'ep_' . $this->slug . '_sync_kill' ) ) {
```
Comment (felipeelia) [inline includes/classes/Indexable.php]:
```suggestion
		if ( apply_filters_deprecated( 'ep_' . $this->slug . '_index_kill', [ false, $object_id ], 'ElasticPress 5.3.3', 'ep_' . $this->slug . '_sync_kill' ) ) {
```

File: includes/classes/IndexHelper.php [hunk 6]
```diff
@@ -1178,24 +1178,31 @@ protected function should_skip_object_index( $indexable_object, $indexable ) {
...
 		 * @hook ep_item_sync_kill
 		 * @param  {boolean} $kill False means dont sync
 		 * @param  {array} $indexable_object Object to sync
 		 * @return {Indexable} Indexable that object belongs to
 		 */
-		$ep_item_sync_kill = apply_filters( 'ep_item_sync_kill', false, $indexable_object, $indexable );
+		$ep_item_sync_kill = apply_filters_deprecated(
+			'ep_item_sync_kill',
+			[ false, $indexable_object, $indexable ],
+			'5.3.3',
```
Comment (felipeelia) [inline includes/classes/IndexHelper.php]:
```suggestion
			'ElasticPress 5.3.3',
```

File: includes/classes/IndexHelper.php [hunk 7]
```diff
@@ -1178,24 +1178,31 @@ protected function should_skip_object_index( $indexable_object, $indexable ) {
...
-		 * @param  {bool} $index True means dont index
-		 * @param  {int} $object_id Object ID
-		 * @return {bool} New value
-		 */
-		$ep_indexable_sync_kill = apply_filters( 'ep_' . $indexable->slug . '_index_kill', false, $indexable_object->ID );
+		/** This filter is documented in includes/classes/Indexable.php */
+		$ep_indexable_index_kill = apply_filters_deprecated(
+			'ep_' . $indexable->slug . '_index_kill',
+			[ false, $indexable_object->ID ],
+			'5.3.3',
```
Comment (felipeelia) [inline includes/classes/IndexHelper.php]:
```suggestion
			'ElasticPress 5.3.3',
```

**Review by felipeelia — CHANGES_REQUESTED** [review]
