### PR TITLE
Fix: All public methods in Command class are treated as a wpcli command 

### LINKED ISSUE #3193: BUG: All public methods in Command class are treated as a wpcli command
### Describe the bug

The `Command` class has a few methods whose visibility is public, and WP CLI treated these methods as a command. For example, if we run `wp elasticpress custom_get_transient` , WordPress treats this [method](https://github.com/10up/ElasticPress/blob/4.0.0/includes/classes/Command.php#L1214) as a command and eventually ends with the errors. 

### Steps to Reproduce

Run WP CLI command `wp elasticpress custom_get_transient`

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress and ElasticPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by burhandodhy**
### Description of the Change

This PR adds a new Helper class for WP CLI commands and move the public method to Helper class so that they will be not treated as CLI command

Closes #3193 

### Changelog Entry

> Fixed - All public methods in Command class are treated as a wpcli command

### Credits

Props @burhandodhy 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/classes/Command.php [hunk 1]
```diff
@@ -16,6 +16,7 @@
 use ElasticPress\Utils as Utils;
 use ElasticPress\Elasticsearch as Elasticsearch;
 use ElasticPress\Indexables as Indexables;
+use ElasticPress\Command\Utility as Utility;
```
Comment (felipeelia) [inline includes/classes/Command.php]: @burhandodhy you don't need to repeat the class name if you are keeping the same. The two lines above the new one have that same problem. `use ElasticPress\Command\Utility` is already enough.

File: includes/classes/Command.php [hunk 2]
```diff
@@ -663,11 +664,8 @@ private function create_network_alias_helper( Indexable $indexable ) {
 	 * @since  3.3
 	 */
 	public function delete_transient_on_int( $signal_no ) {
-		if ( SIGINT === $signal_no ) {
-			$this->delete_transient();
-			WP_CLI::log( esc_html__( 'Indexing cleaned up.', 'elasticpress' ) );
-			WP_CLI::halt( 0 );
-		}
+		_doing_it_wrong( __METHOD__, esc_html__( 'This method is deprecated and will be removed from 5.0. Use \ElasticPress\Command\Utility::delete_transient_on_int instead.', 'elasticpress' ), '4.5.1' );
```
Comment (felipeelia) [inline includes/classes/Command.php]: Instead of `_doing_it_wrong` we should call `_deprecated_function` in all these functions. Also, do you mind reviewing the last parameter of the function? You have it as `'4.5.1'` but that should be 4.5.0.

File: includes/classes/Command/Utility.php [hunk 3]
```diff
@@ -0,0 +1,193 @@
+<?php
+/**
+ * ElasticPress CLI Utility
+ *
+ * @since 4.4.0
```
Comment (felipeelia) [inline includes/classes/Command/Utility.php]: This should be 4.5.0

File: includes/classes/Command/Utility.php [hunk 4]
```diff
@@ -0,0 +1,193 @@
...
+
+/**
+ * Utility class for WP CLI commands.
+ */
+class Utility {
+
+	/**
+	 * Internal timer.
+	 *
+	 * @since 4.2.0
```
Comment (felipeelia) [inline includes/classes/Command/Utility.php]: Although these methods exist before, the `@since` tag should be either removed or updated to 4.5.0, as these are not the (exact) same methods. Let's remove them for now, as all of them are `4.5.0`

**Review by felipeelia — CHANGES_REQUESTED** [review]
@burhandodhy asked for some changes on this one. Although I'm not a fan of introducing a whole new class to fix the original problem, I also see it being valid to separate concerns... 🤔

File: includes/classes/Command.php (hunk 1 above)
Comment (burhandodhy) [reply includes/classes/Command.php]: I followed the same convention. However, I removed the alias from all the classes.

File: includes/classes/Command.php (hunk 2 above)
Comment (burhandodhy) [reply includes/classes/Command.php]: Its done.

File: tests/php/TestCommands.php [hunk 5]
```diff
@@ -12,6 +12,7 @@
 use ElasticPress\Command;
 use ElasticPress\Indexables;
 use ElasticPress\Utils;
+use ElasticPress\Command\Utility as Utility;
```
Comment (felipeelia) [inline tests/php/TestCommands.php]: @burhandodhy we don't need the alias here as well

**Review by felipeelia — CHANGES_REQUESTED** [review]
In addition to the small change that still needs to be done here @burhandodhy, do you mind fixing the git conflict that arose? Thanks.

File: tests/php/TestCommands.php (hunk 5 above)
Comment (burhandodhy) [reply tests/php/TestCommands.php]: Done

File: includes/classes/Command.php [hunk 6]
```diff
@@ -723,9 +721,7 @@ public function delete_transient_on_int( $signal_no ) {
 	 * @param array $assoc_args Associative CLI args.
 	 */
 	public function sync( $args, $assoc_args ) {
-		global $wp_actions;
-
-		$setup_option = \WP_CLI\Utils\get_flag_value( $assoc_args, 'setup', false );
+		$setup_option = isset( $assoc_args['setup'] ) ? $assoc_args['setup'] : false;
```
Comment (felipeelia) [inline includes/classes/Command.php]: @burhandodhy this actually should keep the change introduced in #3301

File: includes/classes/Command.php [hunk 7]
```diff
@@ -821,11 +817,11 @@ public function sync( $args, $assoc_args ) {
 
 		\ElasticPress\IndexHelper::factory()->full_index( $index_args );
 
-		remove_action( 'ep_sync_put_mapping', [ $this, 'stop_on_failed_mapping' ] );
-		remove_action( 'ep_sync_put_mapping', [ $this, 'call_ep_cli_put_mapping' ], 10, 2 );
-		remove_action( 'ep_index_batch_new_attempt', [ $this, 'should_interrupt_sync' ] );
+		remove_action( 'ep_sync_put_mapping', [ Utility::class, 'stop_on_failed_mapping' ] );
+		remove_action( 'ep_sync_put_mapping', [ Utility::class, 'ep_cli_put_mapping' ], 10, 2 );
+		remove_action( 'ep_index_batch_new_attempt', [ Utility::class, 'maybe_interrupt_sync' ] );
```
Comment (felipeelia) [inline includes/classes/Command.php]: Are you sure about these two method names? Shouldn't they be `call_ep_cli_put_mapping` and `should_interrupt_sync`?

File: includes/classes/Command.php [hunk 8]
```diff
@@ -1135,15 +1124,11 @@ function ( $prefix ) use ( $assoc_args ) {
...
-		if ( $should_interrupt_sync ) {
-			WP_CLI::line( esc_html__( 'Sync was interrupted', 'elasticpress' ) );
-			$this->delete_transient_on_int( 2 );
-			WP_CLI::halt( 0 );
-		}
+		_deprecated_function( __METHOD__, '4.5.0', '\ElasticPress\Command\Utility::should_interrupt_sync' );
+		Utility::should_interrupt_sync();
 	}
 
+
```
Comment (felipeelia) [inline includes/classes/Command.php]: It seems a new line was introduced here by accident. Do you mind removing it?

File: includes/classes/Command.php [hunk 9]
```diff
@@ -1337,7 +1297,7 @@ public function index_output( $message, $args, $index_meta, $context ) {
 				break;
 
 			case 'error':
-				$this->clear_sync();
+				Utility::delete_transient();
```
Comment (felipeelia) [inline includes/classes/Command.php]: Making this change we are no longer calling the `ep_cli_before_clear_index` and `ep_cli_after_clear_index` actions. Is there a reason why?

**Review by felipeelia — CHANGES_REQUESTED** [review]
@burhandodhy the conflict was not properly fixed (the new code was reverted.) So I took a deeper look into the code and it seems we still have some inconsistencies and breaking changes. Do you mind giving it another thorough review? Are you 100% sure this does not break any existing behavior including hooks? Thanks.

File: tests/php/TestCommands.php (hunk 5 above)
Comment (felipeelia) [reply tests/php/TestCommands.php]: It seems this wasn't changed @burhandodhy ?

**Review by felipeelia — CHANGES_REQUESTED** [review]
@burhandodhy we are almost there. There is a change that didn't seem to be pushed and also I just remembered we need to change the --remove parameter [here](https://github.com/10up/ElasticPress/blob/develop/.github/workflows/build-docs.yml#L49).
