### PR TITLE
Override ES highlighting in IR

### LINKED ISSUE #3497: BUG: attempting to conduct a search for posts with bracket in the title results in instant Results not displaying brackets
### Describe the bug

When attempting to conduct a search for posts with bracket in the title, I've encountered an issue with the Instant Results feature.

### Steps to Reproduce

The steps to reproduce the issue are as follows:

Create and save a post with the title "Cannon Shot (Far)".
Conduct a search for "Cannon Shot".
Clear the suggestion presented by the Instant Results feature.
Upon performing these steps, the search results unexpectedly alter.

The results change Cannon Shot (Far) to Cannon Shot (Far

**The closing bracket becomes missing.

### Screenshots, screen recording, code snippet

[0398ff31-4c55-4fd1-912e-c06cab09e1df.webm](https://github.com/10up/ElasticPress/assets/108893208/eaa2005c-b80d-4adb-8d20-3f87a2dfecc9)

### Environment information

_No response_

### WordPress and ElasticPress information

`
### wp-core ###

version: 6.2.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /Users/bigsur/Local Sites/elasticpress/app/public
wordpress_size: 129.66 MB (135962564 bytes)
uploads_path: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content/uploads
uploads_size: 6.46 MB (6769713 bytes)
themes_path: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content/themes
themes_size: 37.56 MB (39384693 bytes)
plugins_path: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content/plugins
plugins_size: 83.37 MB (87416631 bytes)
database_size: 2.77 MB (2899968 bytes)
total_size: 259.81 MB (272433569 bytes)

### wp-active-theme ###

name: Twenty Twenty-Two (twentytwentytwo)
version: 1.3 (latest version: 1.4)
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor, wp-block-styles, editor-style
theme_path: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content/themes/twentytwentytwo
auto_update: Disabled

### wp-themes-inactive (5) ###

Konte: version: 2.2.3, author: UIX Themes, Auto-updates disabled
Shopwise: version: 1.6.7, author: KlbTheme (Sinan ISIK), Auto-updates disabled
Storefront: version: 4.2.0, author: Automattic (latest version: 4.3.0), Auto-updates disabled
Twenty Twenty-One: version: 1.7, author: the WordPress team (latest version: 1.8), Auto-updates disabled
Twenty Twenty-Three: version: 1.0, author: the WordPress team (latest version: 1.1), Auto-updates disabled

### wp-plugins-active (3) ###

ElasticPress: version: 4.6.0, author: 10up, Auto-updates disabled
FacetWP: version: 4.1.8, author: FacetWP, LLC (latest version: 4.2.1), Auto-updates disabled
WP Reset: version: 1.97, author: WebFactory Ltd, Auto-updates disabled

### wp-plugins-inactive (9) ###

Ajax Search Pro: version: 4.25.1, author: Ernest Marcinko, Auto-updates disabled
Debug Bar: version: 1.1.4, author: wordpressdotorg, Auto-updates disabled
Debug Bar ElasticPress: version: 3.0.0, author: 10up, Auto-updates disabled
Disable Gutenberg: version: 2.9, author: Jeff Starr, Auto-updates disabled
ElasticPress Labs: version: 2.1.0, author: 10up, Auto-updates disabled
Elementor: version: 3.12.0, author: Elementor.com (latest version: 3.13.4), Auto-updates disabled
Konte Addons: version: 2.1.7, author: UIX Themes, Auto-updates disabled
SearchWP: version: 4.0.18, author: SearchWP, Auto-updates disabled
WooCommerce: version: 7.3.0, author: Automattic (latest version: 7.8.0), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1808
imagemagick_version: ImageMagick 7.1.0-46 Q16 x86_64 5ef3d4d66:20220816 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 1000M
upload_max_filesize: 300M
max_effective_size: 300 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 32 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 32 GB
	imagick::RESOURCETYPE_MEMORY: 16 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: Unable to determine
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 22.3.0 x86_64
httpd_software: Apache/2.4.43 (Unix)
php_version: 8.1.9 64bit
php_sapi: fpm-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 512M
max_input_time: 600
upload_max_filesize: 300M
php_post_max_size: 1000M
curl_version: 7.84.0 (SecureTransport) OpenSSL/1.1.1q
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.16
client_version: mysqlnd 8.1.9
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content
WP_PLUGIN_DIR: /Users/bigsur/Local Sites/elasticpress/app/public/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### ep-last-sync ###

method: WP Dashboard
is_full_sync: Yes
start_date_time: 2023/06/15 4:50:05 pm
end_date_time: 2023/06/15 4:50:18 pm
total_time: 0 hours, 0 minutes, 13 seconds
total: 3
synced: 3
skipped: undefined
failed: undefined
errors: 

### epio-autosuggest ###

post-types: post and page
post-status: publish
search-fields: post_title, post_excerpt, and post_content
returned-fields: ''

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oscarssanchez**
### Description of the Change

This PR overrides the result coming from ES highlight, as noted in https://github.com/10up/ElasticPress/issues/3497 there seems to be an issue with how the highlighter returns results in partial/no matches

We should probably remove when we drop support for ES5
 
Closes https://github.com/10up/ElasticPress/issues/3497

### Changelog Entry

> Fixed - Bug fix - Highlighting returning inaccurate post title when partial/no term match

### Credits

Props @JakePT , @tomi10up, @oscarssanchez, @felipeelia   ...

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: assets/js/instant-results/components/layout/results.js [hunk 1]
```diff
@@ -50,6 +50,15 @@ export default () => {
 		headingRef.current.scrollIntoView({ behavior: 'smooth' });
 	}, [offset]);
 
+	/**
+	 * Note: highlighting is redone here because the unified highlight type is not supported in ES5
+	 */
+	const regex = new RegExp(`\\b(${searchTerm})`, 'gi');
+	searchResults.forEach((hit, index) => {
+		const resultsText = hit._source.post_title.replace(regex, (word) => `<mark>${word}</mark>`);
```
Comment (JakePT) [inline assets/js/instant-results/components/layout/results.js]: @oscarssanchez We should use the tag selected for highlighting from settings here. It should be available as the `highlight` property of `args` here: https://github.com/10up/ElasticPress/blob/95eae3388364a648eb2b819a8bc0ae74c4c84763/assets/js/instant-results/components/layout/results.js#L22 We should also check if this is empty, as if it is empty it means the user has selected no highlighting.

Also, I think I'd rather we do this in the Result component here: https://github.com/10up/ElasticPress/blob/95eae3388364a648eb2b819a8bc0ae74c4c84763/assets/js/instant-results/components/results/result.js, as this is where we a taking the raw response data and preparing it to display in a static component.

In this file, instead of destructuring `highlight.post_title` into `title` I would destructure it with its original `post_title` name, and then I would apply the regex where we're preparing the date, excerpt etc.:

```js
const title = post_title.replace(regex, (word) => `<${tag}>${word}</${tag}>`);
```

(coded blind, so make sure to double check it)

**Review by JakePT — CHANGES_REQUESTED** [review]

File: assets/js/instant-results/components/layout/results.js (hunk 1 above)
Comment (oscarssanchez) [reply assets/js/instant-results/components/layout/results.js]: @JakePT The problem that I see with the proposed approach is that we do not have access to `searchTerm` in result.js as well as the highlighting options. I think we could pass these as a prop if you think that's the best move. 

Alternatively, we could probably iterate through the different search forms and get the search term that way, but we still wouldn't know about the selected highlighting.

Comment (JakePT) [reply assets/js/instant-results/components/layout/results.js]: @oscarssanchez I think pass it through as a prop.

**Review by JakePT — DISMISSED** [review]
