### PR TITLE
Adjust compatibility with `all` for WP_User_Query (WP 6.1)

### LINKED ISSUE #3108: BUG: Unit tests for User feature are failing for WordPress 6.1
**Describe the bug**

 Unit tests for User feature are failing for WordPress 6.1

```
1) ElasticPressTest\TestUser::testBasicUserQuery
Object of class stdClass could not be converted to int

/tmp/wordpress/wp-includes/meta.php:1125
/tmp/wordpress/wp-includes/pluggable.php:128
/tmp/wordpress/wp-includes/class-wp-user-query.php:843
/tmp/wordpress/wp-includes/class-wp-user-query.php:79
/home/runner/work/ElasticPress/ElasticPress/tests/php/indexables/TestUser.php:275

2) ElasticPressTest\TestUser::testUserQueryNumber
Object of class stdClass could not be converted to int

/tmp/wordpress/wp-includes/meta.php:1125
/tmp/wordpress/wp-includes/pluggable.php:128
/tmp/wordpress/wp-includes/class-wp-user-query.php:843
/tmp/wordpress/wp-includes/class-wp-user-query.php:79
/home/runner/work/ElasticPress/ElasticPress/tests/php/indexables/TestUser.php:299
```

**Steps to Reproduce**

1. Run Unit tests.

**Expected behavior**

All tests should pass.

### PR DESCRIPTION
**Pull request by felipeelia**
### Description of the Change

Closes #3108

### Changelog Entry

> Changed - To be compatible with WordPress 6.1, WP_User_Query passing `all` as `fields` parameter value will receive only user IDs.

### Credits

Props @felipeelia @burhandodhy 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: tests/php/indexables/TestUser.php [hunk 1]
```diff
@@ -262,10 +262,7 @@ public function testBasicUserQuery() {
 			]
 		);
 
-		foreach ( $user_query->results as $user ) {
-			$this->assertTrue( empty( $user->elasticsearch ) );
-		}
-
+		$this->assertArrayNotHasKey( 'elasticsearch_success', $user_query->query_vars );
```
Comment (burhandodhy) [inline tests/php/indexables/TestUser.php:265]: @felipeelia shouldn't we use `assertTrue`?

Comment (felipeelia) [reply tests/php/indexables/TestUser.php:265]: In this case we just want to be sure `elasticsearch_success` is actually *not* set there, right?

Comment (felipeelia) [reply tests/php/indexables/TestUser.php:265]: In this case we just want to be sure `elasticsearch_success` is actually *not* set there, right?

**Review by burhandodhy — DISMISSED** [review]

**Review by burhandodhy — APPROVED** [review]
